version: '3.8'

services:
  mysqlsite:
    build:
      context: .
      dockerfile: DockerfileSql
    container_name: datasite1
    environment:
      - MYSQL_ROOT_PASSWORD=pa
      - MYSQL_TCP_PORT=9906
    ports:
      - 3306:9906
    volumes:
      - ./mysql:/var/lib/mysql
    

  websitesite:
    container_name: wwwsite1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=mysqlsite
      - MYSQL_DBPORT=9906
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=pa
      - MYSQL_DBNAME=accordeon
    ports:
      - 8111:80
    depends_on:
      - mysqlsite
    volumes:
      - ./files:/var/www/html
